apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-wine-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fastapi-wine
  template:
    metadata:
      labels:
        app: fastapi-wine
    spec:
      containers:
      - name: fastapi-wine
        image: kennygeorgeds/fastapi-wine-app:v2
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "250m"

